### PR TITLE
Add a JS method for toggling the switch

### PR DESCRIPTION
**Pull request by dkniffin**

### CODE REVIEW

**Comment by dkniffin** [comment]
@ava-cassiopeia I've created this PR, but it looks like the automated tests aren't running. The badge in the readme seems to link to `aeolingamenfel`. Maybe Travis needs to be reconfigured?

**Comment by ava-cassiopeia** [comment]
Oop, just saw this today, had a badly configured email filter, sorry! Yeah it looks like Travis has fully migrated + my username change probably fubared it.

I'll probably just switch this repo over to using GitHub Actions, which I'll try to do tomorrow.

**Comment by ava-cassiopeia** [comment]
When possible, could you pull from `master` to this branch and reupload to this PR? #19 adds GitHub action support to this repo (as opposed to Travis.CI), so as soon as this is synced with `master` tests should run.

**Comment by dkniffin** [comment]
@ava-cassiopeia I just rebased. Looks like it didn't kick off a build 🤔  Do you want me to try creating a new PR?

**Comment by ava-cassiopeia** [comment]
Huh, super weird. Yeah I guess just create a new PR. Sorry for the churn!

If creating the new PR doesn't work, I'll just manually pull your branch and test it and approve it myself.

**Pull request closed without merging**
