### PR TITLE
Add a JS method for toggling the switch

### PR DESCRIPTION
**Pull request by dkniffin**
Creating another PR since the tests didn't run on https://github.com/ava-cassiopeia/simple-switch/pull/18

### CODE REVIEW

**Comment by dkniffin** [comment]
@ava-cassiopeia still no luck :/

**Comment by ava-cassiopeia** [comment]
Hmm, ok I need to do some more debugging, but in the meantime I'll test and approve manually. Thank you for trying that though!

**Comment by ava-cassiopeia** [comment]
Tests look good. This is now published as version `0.8.0` on NPM or [here on GitHub](https://github.com/ava-cassiopeia/simple-switch/releases/tag/v0.8.0).

Thanks for your contribution and patience as I figure the testing strategy out!

**Comment by dkniffin** [comment]
Thanks for merging this and bumping the version! 🎉

**Pull request merged**
